services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  SBUERK\EnsureAdmin\:
    resource: '../Classes/*'

  connection.adminpasswordservice.be_users:
    class: 'TYPO3\CMS\Core\Database\Connection'
    factory:
      - '@TYPO3\CMS\Core\Database\ConnectionPool'
      - 'getConnectionForTable'
    arguments:
      - 'be_users'

  hashinstance.be:
    class: 'TYPO3\CMS\Core\Crypto\PasswordHashing\PasswordHashInterface'
    factory:
      - '@TYPO3\CMS\Core\Crypto\PasswordHashing\PasswordHashFactory'
      - 'getDefaultHashInstance'
    arguments:
      - 'BE'

  SBUERK\EnsureAdmin\Services\AdminPasswordService:
    public: true
    arguments:
      $hashInstance: '@hashinstance.be'
      $connection: '@connection.adminpasswordservice.be_users'

  SBUERK\EnsureAdmin\Commands\AdminEnsureCommand:
    tags:
      - name: 'console.command'
        command: 'sbuerk:admin:ensure'
        description: 'Create or update an admin user'
        schedulable: false

  SBUERK\EnsureAdmin\Commands\PasswordEncodeCommand:
    tags:
      - name: 'console.command'
        command: 'sbuerk:password:encode'
        description: 'Takes a plain password and returns the password hash. Can be used as install tool password.'
        schedulable: false
