name: tests core 10

on:
  push:
  pull_request:
  schedule:
    - cron:  '56 4 * * *'

jobs:
  testsuite:
    name: all tests with core 10
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        php: [ '7.2', '7.3', '7.4' ]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install testing system
        run: Build/Scripts/runTests.sh -p ${{ matrix.php }} -t 10 -s composerUpdate

      - name: Lint PHP
        run: Build/Scripts/runTests.sh -p ${{ matrix.php }} -s lint

      - name: CGL
        if: ${{ matrix.php <= '8.1' }}
        run: Build/Scripts/runTests.sh -n -p ${{ matrix.php }} -s cgl
